apiVersion: backstage.io/v1alpha1
kind: Resource

metadata:
  name: payment-db
  description: PostgreSQL database for payments

  annotations:
    backstage.io/techdocs-ref: dir:.

spec:
  type: database
  owner: group:default/team-payments
