
apiVersion: backstage.io/v1alpha1 
kind: Component 
metadata: 
  name: demo-service 
  description: Demo monitored service 

annotations: 
  prometheus.io/rule: 
    demo_requests_total 
  prometheus.io/alert: all 

spec: 
  type: service 
  lifecycle: production 
  owner: guests
